export const assetManifest = {
  geometry: [
    {
      section: 'igloo',
      key: 'igloo-shell',
      source: '/reference-assets/geometries/igloo.drc',
      dracoAttributes: {
        position: 0,
        normal: 1,
        uv: 2,
        centr: 3,
        rand: 4,
        emission: 5,
        batchId: 6
      },
      dracoAttributeTypes: {
        position: 'Float32Array',
        normal: 'Float32Array',
        uv: 'Float32Array',
        centr: 'Float32Array',
        rand: 'Float32Array',
        emission: 'Float32Array',
        batchId: 'Int32Array'
      }
    },
    { section: 'igloo', key: 'igloo-outline', source: '/reference-assets/geometries/igloo/igloo_outline.drc' },
    { section: 'igloo', key: 'igloo-cage', source: '/reference-assets/geometries/igloo/igloo_cage.drc' },
    { section: 'igloo', key: 'mountain', source: '/reference-assets/geometries/mountain.drc' },
    { section: 'igloo', key: 'igloo-patch', source: '/reference-assets/geometries/igloo/patch.drc' },
    { section: 'igloo', key: 'ground', source: '/reference-assets/geometries/ground.drc' },
    { section: 'igloo', key: 'intro-particles', source: '/reference-assets/geometries/intro_particles.drc' },
    { section: 'cubes', key: 'blurrytext', source: '/reference-assets/geometries/blurrytext.drc' },
    { section: 'cubes', key: 'background-shapes', source: '/reference-assets/geometries/cubes/background_shapes.drc' },
    { section: 'cubes', key: 'cube1', source: '/reference-assets/geometries/cubes/cube1.drc' },
    { section: 'cubes', key: 'cube2', source: '/reference-assets/geometries/cubes/cube2.drc' },
    { section: 'cubes', key: 'cube3', source: '/reference-assets/geometries/cubes/cube3.drc' },
    { section: 'entry', key: 'floor', source: '/reference-assets/geometries/floor.drc' },
    { section: 'entry', key: 'ring', source: '/reference-assets/geometries/shattered_ring.drc' },
    { section: 'entry', key: 'ring-secondary', source: '/reference-assets/geometries/shattered_ring2.drc' },
    { section: 'entry', key: 'smoke-trail', source: '/reference-assets/geometries/smoke_trail.drc' },
    { section: 'entry', key: 'ground-smoke', source: '/reference-assets/geometries/shattered_ring_smoke.drc' },
    { section: 'entry', key: 'ceiling-smoke', source: '/reference-assets/geometries/ceilingsmoke.drc' },
    { section: 'detail', key: 'blurrytext-cylinder', source: '/reference-assets/geometries/blurrytext_cylinder.drc' },
    { section: 'detail', key: 'pudgy', source: '/reference-assets/geometries/pudgy.drc' },
    { section: 'detail', key: 'overpass', source: '/reference-assets/geometries/overpass_logo.drc' },
    { section: 'detail', key: 'abstract', source: '/reference-assets/geometries/abstractlogo.drc' }
  ],
  texture: [
    { section: 'igloo', key: 'igloo-color', source: '/reference-assets/images/igloo/igloo_color.ktx2', colorSpace: 'srgb' },
    { section: 'igloo', key: 'igloo-exploded-color', source: '/reference-assets/images/igloo/igloo_exploded_color.ktx2', colorSpace: 'srgb' },
    { section: 'igloo', key: 'ground-color', source: '/reference-assets/images/igloo/ground_color.ktx2', colorSpace: 'srgb' },
    { section: 'igloo', key: 'ground-glow', source: '/reference-assets/images/igloo/ground_glow.ktx2', colorSpace: 'srgb' },
    { section: 'igloo', key: 'ground-sansigloo-color', source: '/reference-assets/images/igloo/ground_sansigloo_color.ktx2', colorSpace: 'srgb' },
    { section: 'igloo', key: 'mountain-color', source: '/reference-assets/images/igloo/mountain_color.ktx2', colorSpace: 'srgb' },
    { section: 'igloo', key: 'triangles-tiling', source: '/reference-assets/images/igloo/triangles_tiling.ktx2', colorSpace: 'srgb', wrap: 'repeat', repeat: [2, 2] },
    { section: 'igloo', key: 'mosaic-noise', source: '/reference-assets/images/mosaic.ktx2', colorSpace: 'srgb', wrap: 'repeat', filter: 'nearest' },
    { section: 'igloo', key: 'clouds-noise', source: '/reference-assets/images/clouds_noise.ktx2', colorSpace: 'srgb', wrap: 'repeat', repeat: [2, 2] },
    { section: 'igloo', key: 'wind-noise', source: '/reference-assets/images/wind_noise.ktx2', wrap: 'repeat', repeat: [2, 2] },
    { section: 'igloo', key: 'igloo-scene-lut', source: '/reference-assets/images/igloo/igloo_scene.ktx2', kind: 'lut-3d' },
    { section: 'runtime', key: 'scroll-data', source: '/reference-assets/images/runtime/scroll-datatexture.ktx2', wrap: 'repeat', repeat: [2, 2] },
    { section: 'runtime', key: 'frost-data', source: '/reference-assets/images/runtime/frost-datatexture.ktx2', wrap: 'repeat', repeat: [2, 2] },
    { section: 'runtime', key: 'blue-noise', source: '/reference-assets/images/noises/blue-8-128-rgb.ktx2', wrap: 'repeat', repeat: [2, 2] },
    { section: 'cubes', key: 'cubes-environment', source: '/reference-assets/images/cubes_env.exr', kind: 'exr-env' },
    { section: 'cubes', key: 'blurrytext-atlas', source: '/reference-assets/images/cubes/blurrytext_atlas.ktx2', colorSpace: 'srgb', wrap: 'repeat' },
    { section: 'cubes', key: 'dot-pattern', source: '/reference-assets/images/cubes/dot_pattern.ktx2', colorSpace: 'srgb', wrap: 'repeat', repeat: [2, 2] },
    { section: 'cubes', key: 'shapes-blurred', source: '/reference-assets/images/shapes_blurred.ktx2', colorSpace: 'srgb' },
    { section: 'cubes', key: 'cube-scene', source: '/reference-assets/images/cubes/cube_scene.ktx2', kind: 'lut-3d' },
    { section: 'cubes', key: 'cube1-normal', source: '/reference-assets/images/cubes/cube1_normal.ktx2' },
    { section: 'cubes', key: 'cube1-roughness', source: '/reference-assets/images/cubes/cube1_roughness.ktx2' },
    { section: 'cubes', key: 'cube2-normal', source: '/reference-assets/images/cubes/cube2_normal.ktx2' },
    { section: 'cubes', key: 'cube2-roughness', source: '/reference-assets/images/cubes/cube2_roughness.ktx2' },
    { section: 'cubes', key: 'cube3-normal', source: '/reference-assets/images/cubes/cube3_normal.ktx2' },
    { section: 'cubes', key: 'cube3-roughness', source: '/reference-assets/images/cubes/cube3_roughness.ktx2' },
    { section: 'cubes', key: 'pudgy-inner-color', source: '/reference-assets/images/cubes/pudgy_color.ktx2', colorSpace: 'srgb' },
    { section: 'cubes', key: 'overpass-inner-color', source: '/reference-assets/images/cubes/overpass_logo_color.ktx2', colorSpace: 'srgb' },
    { section: 'cubes', key: 'abstract-inner-color', source: '/reference-assets/images/cubes/abstractlogo_color.ktx2', colorSpace: 'srgb' },
    { section: 'ui', key: 'ui-logo', source: '/reference-assets/ui/logo-datatexture.ktx2' },
    { section: 'ui', key: 'ui-sound', source: '/reference-assets/ui/sound-datatexture.ktx2' },
    { section: 'ui', key: 'ui-font-mono', source: '/reference-assets/fonts/IBMPlexMono-Medium-datatexture.ktx2' },
    { section: 'entry', key: 'floor-color', source: '/reference-assets/images/floor_color.ktx2', colorSpace: 'srgb' },
    { section: 'entry', key: 'ring-color', source: '/reference-assets/images/shattered_ring_color.ktx2', colorSpace: 'srgb' },
    { section: 'entry', key: 'ring-ao', source: '/reference-assets/images/shattered_ring_ao.ktx2' },
    { section: 'entry', key: 'ring-secondary-color', source: '/reference-assets/images/shattered_ring2_color.ktx2', colorSpace: 'srgb' },
    { section: 'entry', key: 'ring-secondary-ao', source: '/reference-assets/images/shattered_ring2_ao.ktx2' },
    { section: 'detail', key: 'detail-perlin', source: '/reference-assets/images/detail/perlin-datatexture.ktx2', colorSpace: 'srgb', wrap: 'repeat', repeat: [2, 2] },
    { section: 'detail', key: 'detail-caustics', source: '/reference-assets/images/detail/caustics.ktx2', colorSpace: 'srgb', wrap: 'repeat', repeat: [2, 2] },
    { section: 'detail', key: 'detail-bokeh', source: '/reference-assets/images/detail/bokeh.ktx2', colorSpace: 'srgb', wrap: 'repeat', repeat: [2, 2] },
    { section: 'detail', key: 'pudgy-color', source: '/reference-assets/images/pudgy_dark_color.ktx2', colorSpace: 'srgb' },
    { section: 'detail', key: 'overpass-color', source: '/reference-assets/images/overpass_logo_dark_color.ktx2', colorSpace: 'srgb' },
    { section: 'detail', key: 'abstract-color', source: '/reference-assets/images/abstractlogo_dark_color.ktx2', colorSpace: 'srgb' }
  ],
  audio: [
    { section: 'global', key: 'music-bg', source: '../www.igloo.inc/assets/audio/music-highq.ogg' },
    { section: 'global', key: 'room-bg', source: '../www.igloo.inc/assets/audio/room.ogg' },
    { section: 'igloo', key: 'manifesto', source: '../www.igloo.inc/assets/audio/manifesto.ogg' },
    { section: 'cubes', key: 'click-project', source: '../www.igloo.inc/assets/audio/click-project.ogg' },
    { section: 'detail', key: 'enter-project', source: '../www.igloo.inc/assets/audio/enter-project.ogg' },
    { section: 'detail', key: 'leave-project', source: '../www.igloo.inc/assets/audio/leave-project.ogg' },
    { section: 'cubes', key: 'beeps', source: '../www.igloo.inc/assets/audio/beeps.ogg' },
    { section: 'cubes', key: 'beeps2', source: '../www.igloo.inc/assets/audio/beeps2.ogg' },
    { section: 'cubes', key: 'beeps3', source: '../www.igloo.inc/assets/audio/beeps3.ogg' },
    { section: 'cubes', key: 'shard', source: '../www.igloo.inc/assets/audio/shard.ogg' },
    { section: 'detail', key: 'project-text', source: '../www.igloo.inc/assets/audio/project-text.ogg' }
  ]
};
